name: health
channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.11
  - conda-forge::pip
  - conda-forge::seaborn
  - conda-forge::matplotlib
  - conda-forge::jupyter
  - conda-forge::pandas
  - conda-forge::numpy
  - conda-forge::pathlib2
  - conda-forge::scikit-learn
  - conda-forge::ipython
  - conda-forge::notebook
  - conda-forge::plotly
  - conda-forge::pyspark
  - conda-forge::kagglehub
  - pip:
    - mlflow
